### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Toumash** [Toumash/webcon-oneline-server#1]
- [x] Sync files from ./src to the guest
- [x] Decide which tool to use 
    - ✔ **chef** - [has a lot of examples from the vagrant box creator](https://github.com/gusztavvargadr/workstations#infrastructure) and works already
    - ansible ❌ [Ansible cannot be installed on a windows machine](https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows). It can only manage windows guests
- [x] Install chief #2 
  - [x] Install IIS
  - [x] Install .net core 
- [x] #3
- [x] Install SQL Server
  - [x] Enable fulltextsearch
- [ ] Run Webcon Installer
  - [x] Install BPS Workflow Server
  - [ ] Install BPS Designer Studio
  - [x] Install BPS Portal
  - [ ] Install BPS Server Search
- [x] #7
- [ ] #6
- [ ] Connect from Designer
- [ ] #5
- [ ] Open IIS ports for viewing webcon from host
- [ ] Add .env config for webcon sample users
- [ ] Add .env config for Active Directory
- [ ] Add .env config for SQL Server connection
- [ ] Install letsencrypt with ssl certs
- [ ] Run Webcon with docker sql
- [ ] Run Webcon on windows docker container
